steps:
  # Step 1: Install Node.js and npm
  - name: 'node'
    entrypoint: 'npm'
    args: ['install']

  # Step 2: Install project dependencies
  - name: 'gcr.io/cloud-builders/npm'
    args: ['install']

  # Step 3: Build and test application
  - name: 'gcr.io/cloud-builders/npm'
    args: ['run', 'build']

  # Step 4: Deploy application (customize as needed)
  - name: 'gcr.io/cloud-builders/gcloud'
    args: ['app', 'deploy']

# (Optional) Add substitutions or environment variables
substitutions:
  _NODE_ENV: 'production'
